### ISSUE TITLE
Project name change: BitFlux

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#289]
~~We need a new name for the project.~~

~~The name shouldn't imply that this is **the** showcase for d3fc (it's just one example of several) and should be more Bitcoin specific.~~

### Update
The new name is: **BitFlux**

References to `d3fc-showcase` should change to `BitFlux`
References to `showcase` should change to `BitFlux`
References to `sc` should change to `bf`

**Comment by djmiley** [comment]
This may help.
https://bitcoin.org/en/vocabulary

**Comment by jackarnstein** [comment]
This all seems fine, but you know you havent changed the d3fc showcase wiki page right?

**Comment by jleft** [comment]
Great, thanks.

Re: wiki page, I hadn't thought of that - thanks for fixing it!

**Comment by tlsim** [comment]
#595
