### ISSUE TITLE
Reset/tracking latest button - when should it be enabled?

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#412]
> There's a slight incoherence in the Reset functionality too: if your selection touch the last data, Reset is off, even if you change the amount of data selected, but reset always reset the amount of data too when you click it.
>
> Either the amount of data is pertinent and should then be also a criteria to enable the button, or the button should just move the current selection to the last point without changing its width

**Comment by rjmcneill** [comment]
I reckon we should have this how it is at the minute, but also have it enabled when the zoom is changed from the default level.
The way I see it, if the user is zoomed in to maximum level, a button to reset the zoom level might be handy.
What does everyone else think?

**Comment by djmiley** [comment]
I think that sounds good, That should simply entail making the reset button active at all times.

**Comment by rjmcneill** [comment]
I wouldn't necessarily say at all times though.
I mean, if they've just clicked it or just loaded the page, it should probably just be disabled.
I think so anyway?

**Comment by Afredon** [comment]
Ideally it would be enabled as soon as the situation differs from what you would get from pressing the reset button. But that's not going to be easy as the effects of the reset button use a magic number and calculations that are out of reach of the Reset button. So either we rework the whole area to have easy ways to share the transformation and spotting whether it is useful to apply it, or we enable it at all time as the worst case will be it does nothing.

**Comment by djmiley** [comment]
Ok, yes, my mistake. I think it means it becomes an initialisation thing, rather than a check on the state of the `viewDomain` or `trackingLatest`

**Comment by jleft** [comment]
How about:
+ enabled/clickable at all times
+ filled-in/lighter fill colour when tracking latest

We could add a hover style too, to emphasise that it is clickable.

**Comment by rjmcneill** [comment]
I'd be happy with that yea!

**Comment by Afredon** [comment]
I'm not sure it will be user-friendly as we mix 2 concepts on the same button
- going to latest
- resizing selection and going to latest
Might be worth to separate in 2 buttons ?

**Comment by rjmcneill** [comment]
The problem with that is it wouldn't match the UX designs then :/

**Comment by Afredon** [comment]
It would be worth getting their input on this (If I didn't state a misunderstanding in my previous comment)

**Comment by jleft** [comment]
Yeah, sounds like this a questions for UX.

**Comment by jleft** [comment]
Confirmed that it works as expected from a UX perspective, but as this conflicts with #412, we'll discuss with the product owner for a (final) decision.

**Comment by jleft** [comment]
> Confirmed that it works as expected from a UX perspective, but as this conflicts with #507, we'll discuss with the product owner for a (final) decision.

Closing: https://github.com/ScottLogic/BitFlux/issues/507#issuecomment-179786938
