### ISSUE TITLE
Layout dimensions

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#480]
Considering sizing on tablet and mobile. Consult with UX as required.

Investigate using CSS media queries - take height into account too.

Desired behaviour:

|                  | Mobile Landscape | Mobile Portrait   | Tablet Landscape | Tablet Portrait   |
|------------------|------------------|-------------------|------------------|-------------------|
| **Navigator**        | Hidden           | Hidden            | Shown | Shown             |
| **Period selection** | Dropdown         | Dropdown          | Tabs             | Tabs          |
| **Clear all button** | Shown            | Shown             | Hidden           | Hidden             |

**Comment by jackarnstein** [comment]
Hiding navigator when on a tablet in landscape removes any clear method of quickly navigating to the newest / most recent point of interest on the charts

**Comment by jackarnstein** [comment]
The clear all button seems to be present all the time. Even when you dont have anything to clear
