### ISSUE TITLE
clicking the nav-bar reset button changes my visible range

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/BitFlux#507]
when I click the arrow to the right of the navigation chart I would expect it to move my current range so that it end at the most recent datapoint. It does this, however, it also changes the overall visible range.

**Comment by tlsim** [comment]
#412

**Comment by jleft** [comment]
As discussed, the behaviour will remain the same as currently implemented - the current range will be moved to the latest data point **and** it will reset the overall visible range.
