### ISSUE TITLE
Refine module/app build process

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#548]
See discussion here: https://github.com/ScottLogic/d3fc-showcase/pull/537#discussion_r49850253

**Comment by tlsim** [comment]
Using Browserify might also simplify things - we don't currently get much benefit (in terms of bundle size) in using rollup, and the tools around Browserify are more mature. I made a start here https://github.com/tlsim/d3fc-showcase/commits/browserify

**Comment by jleft** [comment]
> Using Browserify might also simplify things - we don't currently get much benefit (in terms of bundle size) in using rollup, and the tools around Browserify are more mature. I made a start here https://github.com/tlsim/d3fc-showcase/commits/browserify

Sounds good :)

Another option: use rollup for our code (to allow us to use ES6 modules) and concat/uglifiy to generate a single file with all of our dependencies. In my mind it's fairly simple and should be easy to maintain.

No strong feelings at the moment though - too many options!

**Comment by tlsim** [comment]
The linked comment is no longer relevant due to seedrandom integration for the app only (and not the consumed module).
