### ISSUE TITLE
Latest development can crash when using navigator bar

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/BitFlux#566]
[bug.zip](https://files.zenhub.io/56a24ec3bb42157e137dd326)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Latest dev build can crash if you play with the brush in the navigator bar by dragging one end onto the other. It stops you being able to scroll in/out or clicking and dragging with the mouse on the chart in order to move left/right.

**Comment by rjmcneill** [comment]
Worth testing when #525 goes in

**Comment by jleft** [comment]
Nice find, definitely something which needs to be fixed.

Does this also affect the latest release (0.11.0) http://scottlogic.github.io/BitFlux/master/ or is it a regression since then?

**Comment by jackarnstein** [comment]
I cant seem to replicate it in  http://scottlogic.github.io/BitFlux/master/ at the moment, I will keep tinkering with it just to make sure!

**Comment by jleft** [comment]
Looks like the regression was caused by #558.

**Comment by jdhodges431** [comment]
Can we close this now? #577.

**Comment by jleft** [comment]
Moved to To Test
