### ISSUE TITLE
Secondary charts not visible using Firefox.

### ISSUE THREAD

**Issue by tlsim** [ScottLogic/BitFlux#569]
Firefox 43. develop 936fb28. Regression from 0.11.0.
Toggling a secondary chart from dropdown adds the secondary chart close button, but the secondary chart itself is not visible.
Caused by #558?

**Comment by jackarnstein** [comment]
The click to zoom is also failing on the bottom navigation bar (When you double click to zoom in). Sometimes it works if you double click and quickly move the mouse afterwards, however it isnt very frequent.

[zoomfail.zip](https://files.zenhub.io/56a5fab1abb587fa56519a62)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jdhodges431** [comment]
Can we close this now? #577.

**Comment by jleft** [comment]
Moved to To Test
