### ISSUE TITLE
Navigation bar chart double click zoom only works if you click on the chart

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/BitFlux#573]
When double clicking on a part of the navigation bar to zoom in, it will only zoom if you double click on a part containing orange chart. If you click above it, it wont zoom? This can make it quite tricky to zoom on charts where the orange section is very low.
[zoom failure.zip](https://github.com/ScottLogic/BitFlux/files/104682/zoom.failure.zip)

**Comment by jleft** [comment]
Expected behaviour: do not zoom on double click.
