### ISSUE TITLE
Give visual indication of which indicators have been added

### ISSUE THREAD

**Issue by owennw** [ScottLogic/BitFlux#579]
If there are already indicators added to the chart it would be nice to see in the indicators drop down which have already been selected. Possibly some highlighting or a checked icon of some sort. Same goes for the selected type (candlestick, OHLC etc.)

**Comment by jleft** [comment]
:+1: Definitely agree with this - this has be bugging quite a few people for a while.

I'll organise some UX involvement, then look at getting this implemented.

**Comment by jackarnstein** [comment]
Likewise, I totally agree with this one :) I mentioned it to james and we made a note of it so we could discuss it with the UX lot

**Comment by jleft** [comment]
Desired behaviour:

![selected-indicator-styles](https://cloud.githubusercontent.com/assets/2017615/13216643/f1d0cf3a-d954-11e5-8814-2df093365a73.PNG)

**Comment by jleft** [comment]
Duplicated by #718
