### ISSUE TITLE
Relative strength index gridline widths are inconsistent

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/BitFlux#603]
The top gridlines of the RSI chart contain 2x the number of light grey pixels.
![widthissue](https://cloud.githubusercontent.com/assets/5921987/12812929/d516a328-cb2c-11e5-84af-715f9ef8de7c.png)

**Comment by jackarnstein** [comment]
Does not always seem to happen, but if you add a MACD chart underneath it, you can see that the middle line is different to the upper/lower gridlines.
![gridlinestwo](https://cloud.githubusercontent.com/assets/5921987/12813666/5e8fbfbe-cb31-11e5-9333-3ed1af8001d4.png)

**Comment by jleft** [comment]
Looks like it's probably happening because it'll be dealing with fractions of pixels.

This will probably give use a quick win, without having to round everything:

```css
shape-rendering: crispEdges;
```

**Comment by jackarnstein** [comment]
They are also being rendered on top of the actual chart lines. Image one shows this really clearly.

**Comment by rjmcneill** [comment]
Opened a new issue for @jackarnstein's comment
#610

**Comment by jleft** [comment]
> They are also being rendered on top of the actual chart lines. Image one shows this really clearly.

Good spot - this is coming directly from a d3fc component so I've raised an issue against d3fc too.
