### ISSUE TITLE
RSI gridlines being rendered on top of the line

### ISSUE THREAD

**Issue by rjmcneill** [ScottLogic/BitFlux#610]
![](https://cloud.githubusercontent.com/assets/5921987/12812929/d516a328-cb2c-11e5-84af-715f9ef8de7c.png)

**Comment by jleft** [comment]
Thanks for splitting this up - I already have a fix for this :)

**Comment by jleft** [comment]
https://github.com/ScottLogic/BitFlux/issues/603#issuecomment-179959071

**Comment by jleft** [comment]
This should be fixed in the next release of d3fc

https://github.com/ScottLogic/d3fc/commit/9ae06442a414a6c3d966ab44db9b1f09a6456056
