### ISSUE TITLE
Add crisp edge shape rendering to specific elements

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#613]
I propose we change `shape-rendering: crispEdges` as the default to all top-level chart SVG elements, then override to `auto` for the line, area and point series (or anything that doesn't look so good with this setting).

Alternatively, we can just target specific elements/groups which should have  `shape-rendering: crispEdges`, but I expect this will be the majority.

Related to #603 and #611

**Comment by tlsim** [comment]
Is it just me that likes the antialiasing? Horizontal and vertical lines might benefit from crispEdges / rounding pixel values, but only if the page is not zoomed (e.g grid lines start to disappear at < 100%).

**Comment by jleft** [comment]
I think the antialiasing works well for elements without horizontal/vertical lines - like the line series, area series, point series etc.

I think I prefer the crisper edges for OHLC, candlestick, grid lines, axes etc. e.g.

#### `crispEdges`
![sr-ce](https://cloud.githubusercontent.com/assets/2017615/12882519/19f7d596-ce4a-11e5-983a-0430a3ca4a48.PNG)

#### `auto`
![sr-auto](https://cloud.githubusercontent.com/assets/2017615/12882520/1af5ec08-ce4a-11e5-9d79-9a7e7705ee48.PNG)

**Comment by jdhodges** [comment]
Yeah looks good with crisp edges.

**Comment by rjmcneill** [comment]
Closed in #661
