### ISSUE TITLE
Add option to set which indicators and displayed when the application is initialised

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#657]

**Comment by jdhodges** [comment]
Is this only aimed at setting the indicators upon initialisation? It will cause layout issues if someone tries to change the indicators while the app is running.

**Comment by jleft** [comment]
> Is this only aimed at setting the indicators upon initialisation?

No, should work at any time.

> It will cause layout issues if someone tries to change the indicators while the app is running.

What sort of issues? Have you got an example/steps to reproduce?

**Comment by jdhodges** [comment]
If I run
```
var app = BitFlux.app()
    .fetchCoinbaseProducts(true)
    .indicators(['rsi']);

app.run('#app-container');

app.indicators(['rsi', 'macd']);
```

I get:
![image](https://cloud.githubusercontent.com/assets/14218569/13636623/ba356d44-e5fa-11e5-8334-bdf1d2295f5b.png)

and for
```
var app = BitFlux.app()
    .fetchCoinbaseProducts(true)
    .indicators(['rsi', 'macd']);

app.run('#app-container');

app.indicators(['rsi']);
```
I get:
![image](https://cloud.githubusercontent.com/assets/14218569/13636644/db63689a-e5fa-11e5-9319-1d541bf16243.png)
