### ISSUE TITLE
Investigate sampling data

### ISSUE THREAD

**Issue by jleft** [ScottLogic/BitFlux#674]
https://d3fc.io/components/sampler/largestTriangleOne.html
https://d3fc.io/components/sampler/largestTriangleThreeBucket.html
https://d3fc.io/components/sampler/modeMedian.html

**Comment by jdhodges** [comment]
We can half the render time of the navigator if we use a sampler with a bucket size of 4. This may mean we lose a bit too much detail so 2 or 3 may be preferable, thoughts? 
![image](https://cloud.githubusercontent.com/assets/14218569/13573965/01e91e9c-e47a-11e5-9ebd-7008e286c9ce.png)

**Comment by jdhodges** [comment]
May be worth varying the bucket size based on the number of data points.

**Comment by jleft** [comment]
> May be worth varying the bucket size based on the number of data points.

Sounds like a good idea to me :+1:

How about varying based on the width of the chart too? I.e. Would it make sense to have more buckets with a wider chart? I'm not so sure about this though...
