### ISSUE TITLE
Setting secondary indicators while app is running causes layout issues.

### ISSUE THREAD

**Issue by jdhodges** [ScottLogic/BitFlux#681]
https://github.com/ScottLogic/BitFlux/issues/657#issuecomment-194296517

> If I run
> ```
> var app = BitFlux.app()
>     .fetchCoinbaseProducts(true)
>     .indicators(['rsi']);
> 
> app.run('#app-container');
> 
> app.indicators(['rsi', 'macd']);
> ```
> 
> I get:
> ![image](https://cloud.githubusercontent.com/assets/14218569/13636623/ba356d44-e5fa-11e5-8334-bdf1d2295f5b.png)
> 
> and for
> ```
> var app = BitFlux.app()
>     .fetchCoinbaseProducts(true)
>     .indicators(['rsi', 'macd']);
> 
> app.run('#app-container');
> 
> app.indicators(['rsi']);
> ```
> I get:
> ![image](https://cloud.githubusercontent.com/assets/14218569/13636644/db63689a-e5fa-11e5-9319-1d541bf16243.png)
>

**Comment by jleft** [comment]
Fixed in #749
