### ISSUE TITLE
IE - Navigator axis labels are cut off

### ISSUE THREAD

**Issue by rjmcneill** [ScottLogic/BitFlux#735]
Labels are slightly cut off, bottom border is as well by the looks
![image](https://cloud.githubusercontent.com/assets/10117342/14322353/7c95e83a-fc14-11e5-8588-07403fd0f7a4.png)

**Comment by jdhodges** [comment]
This is an issue with [IE not supporting dominant-baseline](https://msdn.microsoft.com/en-us/library/gg558060(v=vs.85).aspx).

**Comment by jleft** [comment]
Fixed by #792
