### ISSUE TITLE
IE - Y axis labels not centered vertically

### ISSUE THREAD

**Issue by jdhodges** [ScottLogic/BitFlux#738]
![image](https://cloud.githubusercontent.com/assets/14218569/14344395/39671e0e-fc9f-11e5-87e6-0f5ddd0f62ef.png)

**Comment by jdhodges** [comment]
Same as https://github.com/ScottLogic/BitFlux/issues/735#issuecomment-206747226

**Comment by jleft** [comment]
Fixed by #792
