### ISSUE TITLE
version 1.6.0. In Index.html src app.min.js works, but app.js does not work

### ISSUE THREAD

**Issue by saiyadhusain** [ScottLogic/BitFlux#780]
Hi James Leftley,

I've recently come across your bitflux application and it's absoloutely wonderful. I've downloaded the code from Github and followed the instructions in the readme file to get it running. so far, so good. I am now trying to understand the flow of the code by following the application as it executes. the catch is that the index.html includes app.min.js for it's execution. obviously, the minified file is very difficult to follow. When I change the src to point to app.js (instead of app.min.js) in the index file, the application does not work. it gives an error "**Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined**".

I'd appreciate any help you can provide.

Best Regards
Saiyad Hussain

**Comment by jleft** [comment]
Hi Saiyad,

Thanks for the feedback and I'm pleased to hear you like the application!

If you'd like to view the non-minified script, rather than changing the link to the JavaScript app file, I'd suggest that you run the application in development mode. You can do this by running the following command:

```sh
grunt dev
```
Then navigate to the site at http://localhost:8000/. (There's no need need to use `grunt serve` in this case, as `grunt dev` will also start a server for viewing the application.)

**Comment by saiyadhusain** [comment]
Hi James, 

Thanks for the quick response. I'll have a play with grunt dev and get back to you. however, I would like to be able to have the ability to include app.js instead of app.min.js in the index file. I'm looking to integrate the bitflux charting sample into an ionic application that we've built for stock trading. 

Regards
Saiyad

**Comment by jleft** [comment]
No problem, Saiyad. Running the development build  (`grunt build:development`) will include _app.js_ in _index.html_. However, BitFlux isn't designed to be easily integrated into another application (it has a small, fairly inflexible API). [StockFlux](https://github.com/ScottLogic/StockFlux) is an [application which integrates BitFlux](https://github.com/ScottLogic/StockFlux/tree/d686e7fc45ee7dd4bdc47ae4cb75574f994501b9/src/showcase) - it may be worth looking at the approach used there for inspiration.

**Comment by saiyadhusain** [comment]
Hi James, thanks for getting back. the grunt dev did indeed work and solved my immediate problem. Our goal is to integrate BitFlux by giving it it's own dedicated page and passing a scrip name to it (instead of Goog/BTC-USD etc) and connecting the chart to our own data source. so it's not so much integrating as much as embedding. We have taken our first baby steps in that direction and would love your inputs on how it can be done efficiently. Since we're new at this, we are struggling a bit more than anticipated and the while the code has comments, they are not sufficient for us at the moment. Do you have any document that explains the code flow and what sections of the code we should be looking at if we want to make changes.
The current code resizes the width of the chart container when the window is resized, We are looking to do the same with the height of th container as well as introduce an aspect ratio so that when the window width is resized, the chart container resizes its width as well as height. Our next step is to allow the indicators (SMA/Bollinger bands) to be parameterized based on user input. 

any guidance that you can give would be very welcome. We will also have a play with StockFlux to better understand how BitFlux has been used within it. I'm sure it'll give us some ideas.
Saiyad

**Comment by saiyadhusain** [comment]
Hi James, 

any guidance that you can give would be very welcome

Saiyad

**Comment by jleft** [comment]
Hi Saiyad,

Based on what you've described you'd like to achieve, this isn't easily achievable out of the box, as several of the features you'd like we don't support/expose - the project would have to be modified to achieve this.

> Our goal is to integrate BitFlux by giving it it's own dedicated page and passing a scrip name to it (instead of Goog/BTC-USD etc) and connecting the chart to our own data source. 

Data sources are in [src/assets/js/data](https://github.com/ScottLogic/BitFlux/tree/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/js/data) - you can add your own there.

>  Do you have any document that explains the code flow and what sections of the code we should be looking at if we want to make changes.

Currently, we don't have any documentation for this - I'll look to put something together (#414).

> The current code resizes the width of the chart container when the window is resized, We are looking to do the same with the height of th container as well as introduce an aspect ratio so that when the window width is resized, the chart container resizes its width as well as height.

Layout is determined by [src/assets/js/util/layout.js](https://github.com/ScottLogic/BitFlux/blob/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/js/util/layout.js) and the styles, [src/assets/styles](https://github.com/ScottLogic/BitFlux/tree/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/styles). The application is rendered within a div - `div#app-container` - you might find altering [its styles](https://github.com/ScottLogic/BitFlux/blob/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/styles/base.less#L27-L31) useful.

> Our next step is to allow the indicators (SMA/Bollinger bands) to be parameterized based on user input.

You'll need to create UI components for this; we've have followed the [D3  reusable component pattern](https://bost.ocks.org/mike/chart/), but as the UI for indicator params could be fairly complex, this might not be the most appropriate approach in this case.

The indicators themselves are from [d3fc](https://github.com/ScottLogic/d3fc), and are initalised in [src/assets/js/initialiseModel.js](https://github.com/ScottLogic/BitFlux/blob/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/js/initialiseModel.js#L105-L150). They are either added to the [primary chart](https://github.com/ScottLogic/BitFlux/blob/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/js/chart/primary.js) and have their [own chart](https://github.com/ScottLogic/BitFlux/tree/f317f30d95bf6ebb9206c60e11e3fc8c7240f793/src/assets/js/chart/secondary) below the primary chart.

**Comment by saiyadhusain** [comment]
Hi James ,

I am writing an application With Ionic Framework. I used , Ionic Tabs template and I wanted to add a Chart using BitFlux . Its working good when i am using blank page . but problem is when i am using template routing and trying to render chart in chart page then it's not rendering , even there is no issue in console . do you have any idea please share .

Thanks 
Md Saiyad Husain

**Comment by jleft** [comment]
My experience with Ionic is very limited - do you have any more information about the issue or any code to show? A small example which demonstrates the issue would be very useful :smiley:

**Comment by saiyadhusain** [comment]
Hi James ,
 How can i share my code with you ? i will send you ionic project and BitFlux-dev . 

Thanks 
Md Saiyad Husain

**Comment by saiyadhusain** [comment]
Hi James , 
you there ?

**Comment by jleft** [comment]
A minimal example which demonstrates the issue, hosted at [CodePen](http://codepen.io/) (or similar) would be best, if possible, please.

**Comment by saiyadhusain** [comment]
Can you give name of that project in codepen
